apiVersion: v1
kind: Secret
metadata:
  name: app-tier-secret
data: #for base-64 encoded data
  api-key: TFJjQW1NMTkwNHl3ekszZXNY

# api-key secret (only) is equivalent to
# kubectl create secret generic app-tier-secret --from-literal=api-key=LRcAmM1904ywzK3esX